"""Супервизор VPN-endpoint'а внутри того же контейнера.

Панель сама:
  • генерирует vpn.toml / hosts.toml / credentials.toml / rules.toml;
  • запускает trusttunnel_endpoint как дочерний процесс;
  • при смене кредов делает ПОЛНЫЙ рестарт (endpoint по SIGHUP креды не
    перечитывает — только TLS-hosts; проверено на бою в исходном проекте);
  • при смене домена/продлении сертификата делает SIGHUP (без разрыва сессий);
  • читает сертификаты из CERT_DIR/live/<domain>/ (режим external, за nginx)
    либо из выпущенных certbot'ом (режим letsencrypt) — путь один и тот же.
"""
import os
import signal
import subprocess
import threading
import time
from pathlib import Path

from . import config, db

# Полный vpn.toml — точная копия боевого шаблона endpoint'а; подставляем только порт.
_VPN_TOML_TEMPLATE = """# Generated by trusttunnel-web. Do not edit by hand.
listen_address = "0.0.0.0:{port}"
credentials_file = "credentials.toml"
rules_file = "rules.toml"
ipv6_available = false
allow_private_network_connections = false
tls_handshake_timeout_secs = 10
client_listener_timeout_secs = 600
connection_establishment_timeout_secs = 30
tcp_connections_timeout_secs = 604800
udp_connections_timeout_secs = 300
speedtest_enable = false

[forward_protocol]
[forward_protocol.direct]

[listen_protocols]

[listen_protocols.http1]
upload_buffer_size = 32768

[listen_protocols.http2]
initial_connection_window_size = 8388608
initial_stream_window_size = 131072
max_concurrent_streams = 1000
max_frame_size = 16384
header_table_size = 65536

[listen_protocols.quic]
recv_udp_payload_size = 1350
send_udp_payload_size = 1350
initial_max_data = 104857600
max_stream_data_bidi_local = 1048576
max_stream_data_bidi_remote = 1048576
max_stream_data_uni = 1048576
max_streams_bidi = 4096
max_streams_uni = 4096
max_connection_window = 25165824
max_stream_window = 16777216
disable_active_migration = true
enable_early_data = true
message_queue_capacity = 4096
"""

_RULES_TOML_DEFAULT = "# No rules — all connections allowed by default.\n"


# ── Сертификаты ──────────────────────────────────────────────────────────────
def _live_dir() -> Path:
    return Path(config.CERT_DIR) / "live"


def scan_cert_domains() -> list[str]:
    """Домены, для которых в CERT_DIR/live/<domain>/ есть fullchain.pem + privkey.pem."""
    live = _live_dir()
    out: list[str] = []
    try:
        for entry in sorted(live.iterdir()):
            if not entry.is_dir():
                continue
            if (entry / "fullchain.pem").exists() and (entry / "privkey.pem").exists():
                out.append(entry.name)
    except OSError:
        pass
    return out


def cert_paths(domain: str) -> tuple[Path, Path]:
    d = _live_dir() / domain
    return d / "fullchain.pem", d / "privkey.pem"


def cert_present(domain: str) -> bool:
    if not domain:
        return False
    fc, pk = cert_paths(domain)
    return fc.exists() and pk.exists()


def effective_domain(settings: dict[str, str]) -> str:
    """Домен, за которым прячется endpoint: отдельный (домен B) либо домен панели."""
    if settings.get("connection_hidden") == "1":
        return (settings.get("conn_domain") or "").strip()
    return (settings.get("panel_domain") or "").strip()


def ensure_letsencrypt(domain: str, email: str) -> None:
    """Режим letsencrypt: выпустить сертификат подключения через certbot (standalone :80).

    Best-effort: пишет в общий CERT_DIR (тот же, что читает endpoint). Требует, чтобы
    контейнер принимал входящие на 80 для домена (т.е. НЕ за внешним прокси на 80).
    """
    if not domain or cert_present(domain):
        return
    if not email:
        print("[cert] letsencrypt: e-mail не задан — пропускаю выпуск")
        return
    cmd = [
        "certbot", "certonly", "--standalone", "--non-interactive", "--agree-tos",
        "-m", email, "-d", domain,
        "--config-dir", config.CERT_DIR,
        "--work-dir", str(Path(config.CERT_DIR) / "work"),
        "--logs-dir", str(Path(config.CERT_DIR) / "logs"),
    ]
    print(f"[cert] issuing Let's Encrypt certificate for {domain}")
    try:
        subprocess.run(cmd, timeout=180, check=False)
    except (OSError, subprocess.TimeoutExpired) as e:
        print(f"[cert] certbot failed: {e}")


def renew_letsencrypt() -> None:
    """Периодическое продление (certbot renew). Вотчер сертификата сделает SIGHUP."""
    try:
        subprocess.run(
            ["certbot", "renew", "--config-dir", config.CERT_DIR,
             "--work-dir", str(Path(config.CERT_DIR) / "work"),
             "--logs-dir", str(Path(config.CERT_DIR) / "logs"), "--quiet"],
            timeout=300, check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as e:
        print(f"[cert] certbot renew failed: {e}")


# ── Генерация файлов endpoint'а ──────────────────────────────────────────────
def _atomic_write(path: Path, content: str) -> bool:
    """Записать, только если содержимое изменилось. True — если писали."""
    try:
        if path.read_text(encoding="utf-8") == content:
            return False
    except OSError:
        pass
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)
    return True


def write_vpn_toml(port: int) -> bool:
    return _atomic_write(
        Path(config.ENDPOINT_WORKDIR) / "vpn.toml", _VPN_TOML_TEMPLATE.format(port=port)
    )


def ensure_rules_toml() -> None:
    p = Path(config.ENDPOINT_WORKDIR) / "rules.toml"
    if not p.exists():
        _atomic_write(p, _RULES_TOML_DEFAULT)


def write_hosts_toml(domain: str, custom_sni: str = "") -> bool:
    fc, pk = cert_paths(domain)
    sni = custom_sni.strip()
    sni_line = f'allowed_sni = ["{sni}"]' if sni else "allowed_sni = []"
    content = (
        "ping_hosts = []\n"
        "speedtest_hosts = []\n"
        "reverse_proxy_hosts = []\n"
        "\n"
        "[[main_hosts]]\n"
        f'hostname = "{domain}"\n'
        f'cert_chain_path = "{fc}"\n'
        f'private_key_path = "{pk}"\n'
        f"{sni_line}\n"
    )
    return _atomic_write(Path(config.ENDPOINT_WORKDIR) / "hosts.toml", content)


def write_credentials_toml(creds: list[dict]) -> bool:
    lines: list[str] = []
    for c in creds:
        lines.append("[[client]]")
        lines.append(f'username = "{c["username"]}"')
        lines.append(f'password = "{c["password"]}"')
        lines.append("")
    return _atomic_write(
        Path(config.ENDPOINT_WORKDIR) / "credentials.toml", "\n".join(lines)
    )


# ── Менеджер процесса endpoint'а ─────────────────────────────────────────────
class EndpointManager:
    def __init__(self) -> None:
        self._proc: subprocess.Popen | None = None
        self._lock = threading.RLock()
        self._cert_mtime: float | None = None
        self._watcher_stop = threading.Event()

    # -- низкоуровневое управление процессом --
    def _is_running(self) -> bool:
        return self._proc is not None and self._proc.poll() is None

    def _spawn(self) -> None:
        bin_path = Path(config.ENDPOINT_BIN)
        if not bin_path.exists():
            print(f"[endpoint] binary not found at {bin_path}; endpoint disabled")
            return
        try:
            self._proc = subprocess.Popen(
                [str(bin_path), "vpn.toml", "hosts.toml"],
                cwd=config.ENDPOINT_WORKDIR,
            )
            print(f"[endpoint] started (pid={self._proc.pid})")
        except OSError as e:
            print(f"[endpoint] failed to start: {e}")
            self._proc = None

    def _kill(self) -> None:
        if self._is_running():
            assert self._proc is not None
            self._proc.terminate()
            try:
                self._proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self._proc.kill()
        self._proc = None

    # -- публичные операции --
    def reconcile(self, restart_for_creds: bool = False) -> None:
        """Свести файлы endpoint'а к текущим настройкам/кредам и (пере)запустить.

        restart_for_creds=True → форсируем рестарт (смена кредов).
        Иначе: старт, если не запущен; SIGHUP, если менялся hosts.toml/серт.
        """
        with self._lock:
            settings = db.get_settings()
            port = int(settings.get("conn_port", "8443") or "8443")
            domain = effective_domain(settings)
            sni = settings.get("conn_sni", "")

            ensure_rules_toml()
            write_vpn_toml(port)
            creds_changed = write_credentials_toml(db.active_credentials())

            # Режим letsencrypt: пытаемся выпустить серт, если его ещё нет.
            if domain and settings.get("cert_mode") == "letsencrypt" and not cert_present(domain):
                ensure_letsencrypt(domain, settings.get("le_email", ""))

            # Нет домена или сертификата — endpoint не можем поднять с TLS.
            if not domain or not cert_present(domain):
                if not domain:
                    print("[endpoint] no domain configured; endpoint not started")
                else:
                    print(f"[endpoint] certificate for {domain} not found in {config.CERT_DIR}")
                self._kill()
                self._cert_mtime = None
                return

            hosts_changed = write_hosts_toml(domain, sni)
            fc, _ = cert_paths(domain)
            self._cert_mtime = fc.stat().st_mtime

            if not self._is_running():
                self._spawn()
                return
            if restart_for_creds and creds_changed:
                print("[endpoint] credentials changed — restarting")
                self._kill()
                self._spawn()
                return
            if hosts_changed:
                print("[endpoint] TLS host changed — SIGHUP")
                self._sighup()

    def apply_credentials(self) -> None:
        """Вызывать после создания/удаления конфига или блокировки юзера."""
        self.reconcile(restart_for_creds=True)

    def apply_settings(self) -> None:
        """Вызывать после сохранения настроек (домен/порт/серт/SNI)."""
        # Смена порта требует нового listen — надёжнее полный рестарт.
        with self._lock:
            self._kill()
        self.reconcile()

    def _sighup(self) -> None:
        if self._is_running():
            assert self._proc is not None
            try:
                self._proc.send_signal(signal.SIGHUP)
            except OSError as e:
                print(f"[endpoint] SIGHUP failed: {e}")

    def stop(self) -> None:
        with self._lock:
            self._watcher_stop.set()
            self._kill()

    def status(self) -> dict:
        with self._lock:
            settings = db.get_settings()
            domain = effective_domain(settings)
            return {
                "running": self._is_running(),
                "domain": domain,
                "cert_present": cert_present(domain),
                "port": settings.get("conn_port", "8443"),
            }

    # -- фоновый вотчер продления сертификата --
    def start_cert_watcher(self, interval: int = 60) -> None:
        def loop() -> None:
            ticks = 0
            renew_every = max(1, 12 * 3600 // interval)  # certbot renew ~2 раза в сутки
            while not self._watcher_stop.wait(interval):
                ticks += 1
                try:
                    if db.get_setting("cert_mode") == "letsencrypt" and ticks % renew_every == 0:
                        renew_letsencrypt()
                    self._check_cert_renewed()
                except Exception as e:  # вотчер не должен падать
                    print(f"[endpoint] cert watcher error: {e}")

        threading.Thread(target=loop, name="cert-watcher", daemon=True).start()

    def _check_cert_renewed(self) -> None:
        with self._lock:
            settings = db.get_settings()
            domain = effective_domain(settings)
            if not domain or not cert_present(domain):
                return
            fc, _ = cert_paths(domain)
            mtime = fc.stat().st_mtime
            if self._cert_mtime is not None and mtime != self._cert_mtime:
                print(f"[endpoint] certificate for {domain} renewed — SIGHUP")
                self._sighup()
            self._cert_mtime = mtime


manager = EndpointManager()
