server {
    listen 443 ssl;
    server_name onixus-rf.duckdns.org;
    ssl_certificate /certs/live/onixus-rf.duckdns.org/fullchain.pem;
    ssl_certificate_key /certs/live/onixus-rf.duckdns.org/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 3m;
    resolver 127.0.0.11 valid=10s ipv6=off;
    location / {
        set $portal http://trusttunnel-web:8000;
        proxy_pass $portal;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_cookie_flags ~ secure httponly samesite=strict;
        proxy_read_timeout 35s;
    }
}
