[package]
name = "rtrust-ios"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
rtrust-mobile = { path = "../../../crates/mobile" }
rtrust-profile.workspace = true
rtrust-engine.workspace = true
rtrust-tun = { path = "../../tun" }
serde_json.workspace = true
tokio.workspace = true
zeroize.workspace = true
